{
 "title": "Commercial / Marketing",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Nombre d'utilisateurs total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 1, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT\n  count(*)\nFROM user" }
   ]
  },
  {
   "title": "Nombre utilisateurs sur la période",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  count(id)\nFROM user\nWHERE\n  $__timeFilter(created_at)\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "Nombre de snippets total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM snippet"
    }
   ]
  },
  {
   "title": "Nombre snippet sur la période",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  count(id)\nFROM snippet\nWHERE\n  $__timeFilter(created_at)\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "Nouveaux utilisateurs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"nombre\"\nFROM user\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    }
   ]
  },
  {
   "title": "Nouveaux snippets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"nombre\"\nFROM snippet\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    }
   ]
  },
  {
   "title": "Snippets validés",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"nombre\"\nFROM snippet_validation\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    }
   ]
  },
  {
   "title": "Votes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  count(id) AS \"nombre\"\nFROM vote\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY $__timeGroup(created_at,$__interval)"
    }
   ]
  }
 ]
}