{
 "title": "Hardware",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "windows_os_processes" }
   ]
  },
  {
   "title": "CPU frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "windows_cpu_core_frequency_mhz" }
   ]
  },
  {
   "title": "Packets received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_net_packets_received_total"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "windows_system_threads" }
   ]
  },
  {
   "title": "CPU performances",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_cpu_processor_performance"
    }
   ]
  }
 ]
}