name: Cypress tests
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - develop
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQLDATABASE: symfony
        ports:
        - 3306/tcp
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Start mysql service
        run: sudo /etc/init.d/mysql start
        
      - name: Install composer packages
        run: |
          cd ./api/
          composer install
        env:
          APP_ENV: PROD
          DATABASE_URL: mysql://root:root@localhost:3306/symfony
        
      - name: Run migration
        run: |
          cd ./api/
          php bin/console doctrine:database:create
          php bin/console doctrine:migrations:migrate
        env:
          APP_ENV: PROD
          DATABASE_URL: mysql://root:root@localhost:3306/symfony        
          
      - name: Prepare Angular
        run: |
            cd ./web/devctionnary-front/
            sudo npm i -g @angular/cli
            sudo npm install
            npm build

      - name: Launch Symfony
        run: |
          cd ./api/
          php -S localhost:8000 -t ./api/public/ &
        env:
          APP_ENV: PROD
          DATABASE_URL: mysql://root:root@localhost:3306/symfony
        
      - name: Cypress run
        uses: cypress-io/github-action@v2.8.2
        with:
          working-directory: /web/devctionnnary-front
          start: npm start
          wait-on: http://localhost:4200/
          wait-on-timeout: 180
