name: JS Lint

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  run-linters:
    name: Run js linter
    runs-on: ubuntu-latest
    steps:
      - name: Lint in front
        path: ./web/devctionnary-front/.github/workflows
